# Generated by Django 5.0.3 on 2024-03-16 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmission', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transmission',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transmissions', to='transmission.categoria'),
        ),
        migrations.AddField(
            model_name='transmission',
            name='tags',
            field=models.ManyToManyField(related_name='transmissions', to='transmission.tags'),
        ),
        migrations.AddField(
            model_name='transmission',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transmissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='creation_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='transmission_start_date',
            field=models.DateTimeField(),
        ),
    ]
