# Generated by Django 5.0.3 on 2024-03-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmission', '0004_transmission_short_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmission',
            name='short_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
